# Dockerfile.jvm is used for JVM container builds.
FROM eclipse-temurin:17-jre-alpine
WORKDIR /work/
COPY target/wordsearch-1.0-SNAPSHOT-runner.jar /work/
ENTRYPOINT ["java", "-jar", "wordsearch-1.0-SNAPSHOT-runner.jar"]
