# Dockerfile.native-micro is deprecated for this project. Use Dockerfile.jvm for JVM container builds.
# FROM scratch
# COPY target/*-runner /work/
# ENTRYPOINT ["/work/wordsearch-1.0-SNAPSHOT-runner"]

